name: 'coverage'
on:
  push:
    branches: [ main ]
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - uses: ziishaned/jest-reporter-action@v0.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          test-command: npm run test:coverage
          #github-token: ${{ secrets.SECRET_TOKEN }}
          #test-command: "yarn run test:coverage"
#      - uses: ArtiomTr/jest-coverage-report-action@v2
#        with:
#          package-manager: yarn
#          test-script: yarn run test:coverage