name: publish package

on:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          cache: 'yarn'
      - run: yarn install
      - run: yarn run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          cache: 'yarn'
      - run: yarn install
      - run: yarn run test:coverage
      # https://github.com/codecov/codecov-action
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          flags: unittests
          name: codecov-umbrella
          verbose: true

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - run: yarn run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

#  slack:
#    name: Slack
#    needs: build
#    runs-on: ubuntu-latest
#    if: always()
#    steps:
#      # run this action to get workflow conclusion
#      # You can get conclusion by env (env.WORKFLOW_CONCLUSION)
#      - uses: technote-space/workflow-conclusion-action@v1
#      - uses: 8398a7/action-slack@v3
#        with:
#          status: failure
#          fields: repo,message,commit,author,action,eventName,ref,workflow # selectable (default: repo,message)
#        env:
#          GITHUB_TOKEN: 0cf3ea6197802cb49514ea0ec9659111f2add1d6 # optional
#          SLACK_WEBHOOK_URL: ${{secrets.slack_webhook_url}} # required
#        if: env.WORKFLOW_CONCLUSION == 'failure'

